---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-arm
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: nginx
        image: arm64v8/nginx:latest
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
        ports:
        - containerPort: 80
