---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  ttlSecondsAfterEmpty: 60  # scale down nodes after 60 seconds without workloads (excluding daemons)
  ttlSecondsUntilExpired: 86400  # expire nodes after 1 day (in seconds) = 60 * 60 * 24
  limits:
    resources:
      cpu: 5  # limit to 5 CPU cores
  requirements:
  - key: kubernetes.io/os
    operator: In
    values: ["linux"]
  # Include both CPU architectures according to task
  - key: kubernetes.io/arch
    operator: In
    values: ["amd64", "arm64"]
  # Include general purpose instance families
  - key: karpenter.k8s.aws/instance-family
    operator: In
    values: ["t4g", "t2"]
    # Use only small instance sizes to minimize costs.
  - key: karpenter.k8s.aws/instance-size
    operator: In
    values: ["nano", "micro", "small"]
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["on-demand"]
  providerRef:
    name: my-provider
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-provider
spec:
  subnetSelector:
    kubernetes.io/cluster/{{ .Values.cluster_name }}: owned
  securityGroupSelector:
    kubernetes.io/cluster/{{ .Values.cluster_name }}: owned
